name: "Terraform Workflow"

on:
  push:
    branches: [ "pipeline_automate" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: 'us-east-1'
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      if: github.event_name == 'push'
      run: terraform validate

    - name: Terraform format
      id: fmt
      if: github.event_name == 'push'
      run: terraform fmt

    - name: Terraform plan
      id: plan
      if: github.event_name == 'push'
      run: terraform plan -no-color
      
